### ISSUE TITLE
Getting "missing field `disk_reads`" error on startup

### ISSUE THREAD

**Issue by antoinekm** [maxmindlin/rabbitui#1]
Hi @maxmindlin,

I'm getting this error when launching this tool:
```rs
Failed to ping RabbitMQ API: reqwest::Error { kind: Decode, source: Error("missing field `disk_reads`", line: 1, column: 985) }
Check that the service is running and that creds are correct.
``` 

Any idea how I can fix this?

**Comment by maxmindlin** [comment]
Thanks for the issue @AntoineKM . Can you confirm that the management plugin is running on your RMQ instance and that you provided the correct port?  I havent been using RMQ lately so its also possible the most recent version changed their API.

you should be able to hit the `/api/overview` endpoint using your browser or a http client of your choice to see what the cli is using to ping the api server.

**Comment by antoinekm** [comment]
Here is my environment:
<img width="443" alt="image" src="https://github.com/maxmindlin/rabbitui/assets/54948363/d0670c0e-b073-4f1a-a4b0-94ef3ffcd3bd">

`/api/overview` using http (with `disk_reads` missing):
<img width="1486" alt="image" src="https://github.com/maxmindlin/rabbitui/assets/54948363/54ac1fdb-5be3-4933-9a07-dfd3d308762f">

**Comment by antoinekm** [comment]
The problem was really very simple, I just needed a producer and a consumer connected to my RMQ because as you can see above `message_stats` is an empty object.

**Comment by maxmindlin** [comment]
Ah thanks for looking into that. Not sure if it warrants any changes on this end just yet, but happy you figured it out!
